--crearemos una tabla simple para probar el poder de pl sql

CREATE TABLE DANCE (ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);

--PRENDEMOS EL SERVIDOR EN MODO DE DESARROLLADOR

SET SERVEROUTPUT ON;
--VAMOS A EMPEZAR CON UN BLOQUE PL SQL
DECLARE
--AQUI SE DECLARAN LAS VARIABLES A USARSE
EDAD INTEGER;
YEARS INTEGER;
BEGIN
--AQUI VA LA LÓGICA DE TU PROGRAMITA
YEARS:=21;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DÍAS ES '||EDAD);

END;
/
